PostgreSQL:
  restart: always
  image:  postgres
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=postgres
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql